# 通用参数
general:
  image_queue_size: 100
  max_time_diff: 0.06  # 同步数据允许的最大时间差（秒）
  use_tf: false
  output_topic: "/sensing/lidar/points_rgb"  # 合并后的输出话题
  bag_file_path: "/home/ipc/pix/robobus_mapping_web/rosbag2"  # 输出的bag文件路径
  params_file_path: "/home/ipc/pix/parameter/sensor_kit/robobus_sensor_kit_description"

# 73th
# tf2 lidar -> base_link 点云话题配置
pointcloud_topics:
  - topic: "/sensing/lidar/front_top/points"
    frame_id: "lidar_ft_base_link"
    
  - topic: "/sensing/lidar/rear_top/points" 
    frame_id: "lidar_rt_base_link"

# tf2 base_link -> camera 图像话题配置
image_topics:
  - topic: "/electronic_rearview_mirror/front_3mm/camera_image_jpeg"
    name: "camera1_params"
    frame_id: "camera1/camera_link"
      
  - topic: "/electronic_rearview_mirror/rear_3mm/camera_image_jpeg"
    name: "camera2_params"
    frame_id: "camera2/camera_link"
